services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./instance:/home/deployer/data
      - ./uploads:/home/deployer/uploads
    environment:
      - PORT=8000
      - DATABASE_URL=sqlite:////home/deployer/data/swimmers.db
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - UPLOAD_FOLDER=/home/deployer/uploads
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
    - app-network

  worker:
    build: .
    command: uv run python src/consumers/swim_data_worker.py
    volumes:
      - ./instance:/home/deployer/data
      - ./uploads:/home/deployer/uploads
    environment:
      - DATABASE_URL=sqlite:////home/deployer/data/swimmers.db
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - UPLOAD_FOLDER=/home/deployer/uploads
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - prometheus

volumes:
  prometheus_data:
  grafana_data:

networks:
  app-network:
    driver: bridge
