services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./instance:/home/deployer/data
    environment:
      - PORT=5000
      - DATABASE_URL=sqlite:////home/deployer/data/swimmers.db
